package dao;
// Generated 30-abr-2012 18:20:00 by Hibernate Tools 3.2.1.GA


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;

/**
 * Erabiltzailea generated by hbm2java
 */
public class Espezialista_Txostena  implements java.io.Serializable {

     @Size(min=8,max=9,message=" zenbakia ez da zuzena, 8 edo 9 karaktere eduki behar ditu")
     private int zenbakia;
     
     
     private int konsulta;
     
 
     @Size(min=1,max=1000,message="Txostena luzegia")
     private String txostena;
    
     

    public Espezialista_Txostena() {
    }

	
    public Espezialista_Txostena(int zenbakia,  int konsulta, String txosten ) {
       
        this.zenbakia = zenbakia;
        this.konsulta = konsulta;
      
        this.txostena=txosten;
        

    }

    public int getZenbakia() {
        return zenbakia;
    }

    public void setZenbakia(int zenbakia) {
        this.zenbakia = zenbakia;
    }

    public int getKonsulta() {
        return konsulta;
    }

    public void setKonsulta(int konsulta) {
        this.konsulta = konsulta;
    }


    public String getTxostena() {
        return txostena;
    }

    public void setTxostena(String txostena) {
        this.txostena = txostena;
    }

   


}


