package dao;
// Generated 30-abr-2012 18:20:00 by Hibernate Tools 3.2.1.GA


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;

/**
 * Erabiltzailea generated by hbm2java
 */
public class Froga  implements java.io.Serializable {

     @Size(min=8,max=9,message="GSZ zenbakia ez da zuzena, 8 edo 9 karaktere eduki behar ditu")
     private int zenbakia;
     
     private Erizaina erizaina;
     private int konsulta;
      
     @Size(min=1,max=50,message="Karaktere kopurua ez da zuzena, gutxienez 1 eta gehienez 50")
     private String tokia;
     
     @Size(min=1,max=50,message="Karaktere kopurua ez da zuzena, gutxienez 1 eta gehienez 50")
     private Date eguna;
     
     @Size(min=1,max=50,message="Karaktere kopurua ez da zuzena, gutxienez 1 eta gehienez 50")
     private String proba;
    

    public Froga() {
    }

	
    public Froga(int zenbakia,  Erizaina Erizaina, int konsulta ,String tokia, Date eguna,String proba ) {
        this.erizaina = Erizaina;
        this.zenbakia = zenbakia;
        this.tokia = tokia;
        this.eguna = eguna;
        this.konsulta = konsulta;
        this.proba=proba;
        

    }

    public int getZenbakia() {
        return zenbakia;
    }

    public void setZenbakia(int zenbakia) {
        this.zenbakia = zenbakia;
    }

    public Erizaina getErizaina() {
        return erizaina;
    }

    public void setErizaina(Erizaina erizaina) {
        this.erizaina = erizaina;
    }

   

    public int getKonsulta() {
        return konsulta;
    }

    public void setKonsulta(int konsulta) {
        this.konsulta = konsulta;
    }

    public String getTokia() {
        return tokia;
    }

    public void setTokia(String tokia) {
        this.tokia = tokia;
    }

    public Date getEguna() {
        return eguna;
    }

    public void setEguna(Date eguna) {
        this.eguna = eguna;
    }

    public String getProba() {
        return proba;
    }

    public void setProba(String proba) {
        this.proba = proba;
    }

   

}


