package dao;
// Generated 30-abr-2012 18:20:00 by Hibernate Tools 3.2.1.GA


import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;

/**
 * Erabiltzailea generated by hbm2java
 */
public class Historiala  implements java.io.Serializable {

     @Size(min=8,max=9,message="GSZ zenbakia ez da zuzena, 8 edo 9 karaktere eduki behar ditu")
     private int zenbakia;
    
     private Gaixoa gaixoa;
     private int konsulta;
     
     @Size(min=1,max=1000,message="Karaktere kopurua ez da zuzena, gutxienez 1 eta gehienez 50")
     private String deskribapena;
     

    public Historiala() {
    }

	
    public Historiala(int zenbakia, Gaixoa GSZ,int konsulta, String deskrib  ) {
        this.gaixoa = GSZ;
        this.zenbakia = zenbakia;
       this.konsulta = konsulta;
        this.deskribapena = deskrib;
    }

    public int getZenbakia() {
        return zenbakia;
    }

    public void setZenbakia(int zenbakia) {
        this.zenbakia = zenbakia;
    }

    public Gaixoa getGaixoa() {
        return gaixoa;
    }

    public void setGaixoa(Gaixoa gaixoa) {
        this.gaixoa = gaixoa;
    }

    public int getKonsulta() {
        return konsulta;
    }

    public void setKonsulta(int konsulta) {
        this.konsulta = konsulta;
    }

  

    public String getDeskribapena() {
        return deskribapena;
    }

    public void setDeskribapena(String deskribapena) {
        this.deskribapena = deskribapena;
    }

  
  
   
    


}


