package dao;
// Generated 30-abr-2012 18:20:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * Erabiltzailea generated by hbm2java
 */
public class Langilea  implements java.io.Serializable {

     @Size(min=8,max=9,message="GSZ zenbakia ez da zuzena, 8 edo 9 karaktere eduki behar ditu")
     private int ID;
     
     
     @Size(min=1,max=50,message="Karaktere kopurua ez da zuzena, gutxienez 1 eta gehienez 50")
     private String izena;
     
     @Size(min=1,max=50,message="Karaktere kopurua ez da zuzena, gutxienez 1 eta gehienez 50")
     private String abizena;
     
     @Size(min=9,max=9,message="Karaktere kopurua ez da zuzena, 9 izan behar da")
     private int telefonoa;
     
     @Size(min=6,max=6,message="Karaktere kopurua ez da zuzena, 6 izan behar int ID, String izena, String abizena, int telefonoa, String pasahitza, String helbideada ")
     private String pasahitza;
     
    

    public Langilea() {
    }

	
    public Langilea(int ID, String izena, String abizena, int telefonoa, String pasahitza) {
        this.ID = ID;
        this.izena = izena;
        this.abizena = abizena;
        this.pasahitza = pasahitza;
        this.telefonoa = telefonoa;
       

    }

    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getIzena() {
        return izena;
    }

    public void setIzena(String izena) {
        this.izena = izena;
    }

    public String getAbizena() {
        return abizena;
    }

    public void setAbizena(String abizena) {
        this.abizena = abizena;
    }

    public int getTelefonoa() {
        return telefonoa;
    }

    public void setTelefonoa(int telefonoa) {
        this.telefonoa = telefonoa;
    }

    public String getPasahitza() {
        return pasahitza;
    }

    public void setPasahitza(String pasahitza) {
        this.pasahitza = pasahitza;
    }

   
   
    


}


