package dao;
// Generated 30-abr-2012 18:20:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * Erabiltzailea generated by hbm2java
 */
public class Sendagile_Berezia  implements java.io.Serializable {

     @Size(min=8,max=9,message="GSZ zenbakia ez da zuzena, 8 edo 9 karaktere eduki behar ditu")
     private int ID;
      @Size(min=1,max=45,message="Karaktere kopurua ez da zuzena, gutxienez 1 eta gehienez 45")
     private String espezialitatea;
     private Set<Konsulta_Berezia> konsultak = new HashSet<Konsulta_Berezia>(0);
    
    public Sendagile_Berezia() {
    }

	
    public Sendagile_Berezia(int ID, String esp) {
        this.ID = ID;
       this.espezialitatea=esp;
       
    }

    public Sendagile_Berezia(int ID, String esp,Set<Konsulta_Berezia> konsultak ) {
        this.ID = ID;
       this.espezialitatea=esp;
       this.konsultak=konsultak;
    }
    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public String getEspezialitatea() {
        return espezialitatea;
    }

    public void setEspezialitatea(String espezialitatea) {
        this.espezialitatea = espezialitatea;
    }

    public Set<Konsulta_Berezia> getKonsultak() {
        return konsultak;
    }

    public void setKonsultak(Set<Konsulta_Berezia> konsultak) {
        this.konsultak = konsultak;
    }
    

   
   
   
    


}


