package dao;
// Generated 30-abr-2012 18:20:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * Erabiltzailea generated by hbm2java
 */
public class Sendagilea  implements java.io.Serializable {

     @Size(min=8,max=9,message="GSZ zenbakia ez da zuzena, 8 edo 9 karaktere eduki behar ditu")
     private int ID;
    
    public Sendagilea() {
    }

	
    public Sendagilea(int ID) {
        this.ID = ID;
       
    }
    


    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }


   
   
   
    


}


