package dao;
// Generated 30-abr-2012 18:20:00 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

/**
 * Erabiltzailea generated by hbm2java
 */
public class Sendagile_Orokorra  implements java.io.Serializable {

     @Size(min=8,max=9,message="GSZ zenbakia ez da zuzena, 8 edo 9 karaktere eduki behar ditu")
     private int ID;
          private Set<Konsulta_Orokorra> konsultak = new HashSet<Konsulta_Orokorra>(0);

    
    public Sendagile_Orokorra() {
    }

	
    public Sendagile_Orokorra(int ID) {
        this.ID = ID;
       
    }
    public Sendagile_Orokorra(int ID,Set<Konsulta_Orokorra> konsultak) {
        this.ID = ID;
        this.konsultak=konsultak;
       
    }
    public int getID() {
        return ID;
    }

    public void setID(int ID) {
        this.ID = ID;
    }

    public Set<Konsulta_Orokorra> getKonsultak() {
        return konsultak;
    }

    public void setKonsultak(Set<Konsulta_Orokorra> konsultak) {
        this.konsultak = konsultak;
    }
    

   
   
    
   
    


}


